### ISSUE TITLE
After using the script, batocera is not booting missin a default or UI configuration directive

### ISSUE THREAD

**Issue by yandritos** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#2]
Hi,

First thanks for all this nice work. 
I am using a regular pc: intel core 2 quad Q9550 @3.5GH, 4gb ram and an ATI 4980 1GB.
For testing I am using a monitor CRT LG flatron F900p

After using the script (for the option arcade_15_24_31 tri sync), batocera stops to work with this output at screen:

-----------------------------------------------------------------------------
SYSLINUX 6.03 EDD Copyright (C) 1994-2014 H. Peter Anvin et al
No DEFAULT or UI configuration directive found!
boot:
----------------------------------------------------------------------------

Just as a request/suggestion, my Naomi cabinet has a sanwa monitor with the only supported frequency 31khz (640p), could you please prepare a profile/preset for "arcade_31"? I can boot at 15Khz, it could kill the monitor chasis :(

Any additional information you need, please, let me know.

Thanks again and best regards!

**Comment by Redemp** [comment]
We are looking into supporting 31khz monitors..

**Comment by yandritos** [comment]
Hi, sorry the error was my fault. Rion was helping me to detect that I was using the wrong driver selecting ATI instead of Radeon. The script works as expected and thanks to Rion now I am able to work with 31Khz only 640p.

Thanks for all!

**Comment by yandritos** [comment]
Hi, sorry the error was my fault. Rion was helping me to detect that I was using the wrong driver selecting ATI instead of Radeon. The script works as expected and thanks to Rion now I am able to work with 31Khz only 640p.

Thanks for all!
