### ISSUE TITLE
Some game on various system black screen

### ISSUE THREAD

**Issue by RobertoLanzeni** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#58]
Hi there. Other issues i found it. 
After using script, some platforms no more working... black screen and freez system PSX and some other platforms are out of synch.
How can I set single emulator at resolution <= 640*480??  
I'm using ATI Radeon 3000 card. VGA Output

**Comment by RobertoLanzeni** [comment]
Maybe should I configure manually each single core example neogeo.cfg in /userdata/system/.config/retroarch/config/* ??

**Comment by Redemp** [comment]
Looks like your card can't handle a dotclock of 0
Change your dotclock to something other then 0

https://wiki.batocera.org/batocera-and-crt#testing_modelines
