### ISSUE TITLE
wrongly named video connector on DVI

### ISSUE THREAD

**Issue by FrankBG** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#64]
Hi!
I am testing the script on a Fujitsu Futro S920, dvi port, (radeon Driver) and seems that the script detects my graphic port as "DVI-0n", instead of DVI-0 (on V36 beta: batocera-x86_64-36-20230217.img.gz).

This wrong name is carried to the scripts:
/userdata/system\scripts/first_script.sh
/userdata/system/custom-es-config

As a result ES does not start.

I think I have found the error in the script, in line 738 it does:

`video_modeline=$term_DVI-$((nbr-1))n`

Just deleting that "n" from the end of the line, the script is fixed.

Thanks you!

**Comment by ZFEbHVUE** [comment]
Hi Franck,

Yes It is a issue

Shit I believed i corrected it time ago .... 

Thx to you

**Comment by Redemp** [comment]
Fixed with commit [#65 ](url)

Closing
