### ISSUE TITLE
wrong line in resulting mame.ini

### ISSUE THREAD

**Issue by FrankBG** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#68]
Hi!

I have found the following value in mame.ini: 
`dotclock_min              [dotclock_min_value]`
it looks like the script hasn't set it.

Fujitsu Futro S920, dvi port, radeon Driver, Vertical setup (on V36 beta: batocera-x86_64-36-20230217.img.gz).

**Comment by ZFEbHVUE** [comment]
Thx franGB 

The good line is :
dotclock_min              [dotclock_min_mame]

ZFEbHVUE
