### ISSUE TITLE
Double monitor type selection

### ISSUE THREAD

**Issue by yavimaya** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#75]
Double monitor type selection:
![imagen](https://user-images.githubusercontent.com/45275350/221231475-73829e01-26a5-4ac3-a5a4-c6f9ba78ca5a.png)

**Comment by ZFEbHVUE** [comment]
Thx yavimaya ;)
I did your correction on my script . Very ugly past :-)

See you
