### ISSUE TITLE
Default font used in mame.ini.

### ISSUE THREAD

**Issue by sirmagb00** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#8]
in the file:
mame.ini-switchres-generic-v35 o 36 
In the sources to use for mame it says default when it should be:
uifont uismall.bdf
In the version mame.ini-switchres-generic-v32 it is correct.
With the default fonts it is impossible to see the mame configuration menus.

**Comment by Redemp** [comment]
Thank you for that detailed bug report. I will have a look at the issue during this week 👍

**Comment by Redemp** [comment]
Fixed
