### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by sidneyveroneze** [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35#84]
Hello RGB Guys!

I have a Radeon HD4670 Card and I use a VGA->Component Converter from Jasnet to connect it to a Toshiba TV.
This set works normally in GroovyArcade but does not work in Batocera V35, it simply does not send an image to the TV after the script is executed.
During the execution of the script I already tried using the AMDGPU and RADEON drivers, I already tested arcade_15, arcade_15ex, generic_15 monitors, is there anything I can test to solve this issue?

**Comment by Redemp** [comment]
First and foremost Radeon HD4670 doesn't support Amdgpu drivers only Radeon.

**Comment by Redemp** [comment]
Join the discord channel so we can debug the issue.

**Comment by sidneyveroneze** [comment]
Hi, my Discord contact is Sidão#5858.  

Thanks a Lot.

**Comment by Redemp** [comment]
Issue resolved. 
RTFM user error..
